[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "napari-frontveg"
description = "FrontVeg: A Semantic-Geometric Fusion Pipeline for Precision Phenotyping"
authors = [
    { name = "A Djalil", email = "[abdouldjalilo@gmail.com]" }  
]
requires-python = ">=3.10"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Napari",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
    "napari>=0.4.18",
    "napari-plugin-engine>=0.3.0",
    "numpy>=1.22.0",
    "scipy>=1.8.0",
    "scikit-image>=0.19.0",
    "opencv-python>=4.7.0",
    "Pillow>=9.0.0",
    "tqdm>=4.64.0",
    "pyqt5>=5.15.7",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-qt>=4.0.0",
    "pytest-cov>=3.0.0",
]

[project.gui-scripts]
napari-frontveg = "napari_frontveg._dock_widget:napari_plugin_activities"

# [build-system]
# requires = ["setuptools", "wheel", "setuptools_scm"]
# build-backend = "setuptools.build_meta"

[tool.setuptools_scm]