[metadata]
name = frontvegV2
version = 0.1.0
author = Abdoul Djalil OUSSEINI HAMZA
description = Foreground-Aware Zero-Shot Plant Trait Segmentation 
classifiers =
    Framework :: napari

[options]
packages = find_namespace:
package_dir =
    =src
include_package_data = True
install_requires =
    napari[all]
    numpy==1.26.4
    opencv-python==4.8.1.78
    pillow
    scipy
    matplotlib
    einops
    triton-windows
    triton; sys_platform == 'linux'
    setuptools==69.5.1
    scikit-learn
    decord
    psutil
    pycocotools
    pandas
    scikit-image

[options.extras_require]
dev =
    setuptools==69.5.1
    scikit-learn
    decord
    psutil



[options.packages.find]
where = src

[options.entry_points]
napari.manifest =
    frontvegV2 = napari_frontveg:napari.yaml

