[metadata]
name = frontvegV2
version = 0.1.0
author = Abdoul Djalil OUSSEINI HAMZA
description = Foreground-Aware Zero-Shot Plant Trait Segmentation V2
classifiers =
    Framework :: napari

[options]
packages = find:
package_dir =
    =src
include_package_data = True
install_requires =
    napari[all]



[options.packages.find]
where = src

[options.entry_points]
napari.manifest =
    frontvegV2 = napari_frontveg:napari.yaml

