[metadata]
name = napari-frontveg
author = Abdoul Djalil OUSSEINI HAMZA
description = Geometry-Constrained Semantic Segmentation via Vision-Language Priors
classifiers =
    Framework :: napari

[options]
packages = find:
package_dir =
    =src
include_package_data = True
install_requires =
    napari[all]

setup_requires = setuptools_scm
use_scm_version = True

[options.packages.find]
where = src

[options.entry_points]
napari.manifest =
    napari-frontveg = napari_frontveg:napari.yaml

